name: embark2021_adastra
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0 #for handling SVG files
  url_launcher: ^6.0.10
  path_provider: ^2.0.4
  open_file: ^3.2.1
  syncfusion_flutter_pdfviewer: ^19.2.62-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/footer/facebook.png
    - assets/footer/instagram.png
    - assets/footer/twitter.png
    - assets/icons/embark_normal_logostyle.svg
    - assets/images/index/buttons/arrow.png
    - assets/images/index/cheerleader_1.png
    - assets/images/index/cheerleader_2.png
    - assets/images/index/cloud_1.gif
    - assets/images/index/cloud_2.gif
    - assets/images/index/drummer.png
    - assets/images/index/face.gif
    - assets/images/index/flying_book_green.png
    - assets/images/index/flying_book_peach.png
    - assets/images/index/star.gif
    - assets/images/index/buttons/Group_128.png
    - assets/images/landing/flying_book_green.png
    - assets/images/landing/pixels_big.png
    - assets/images/landing/pixels_small.png
    - assets/images/landing/taft_sign.png
    - assets/Embark_7.pdf
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DalaFloda
      fonts:
        - asset: fonts/DalaFloda-Bold.otf
    
    - family: SFPro
      fonts:
        - asset: fonts/SF-Pro-Display-Black.otf
    
    - family: Calibre
      fonts:
        - asset: fonts/calibre_font/Calibre-Regular.otf
        - asset: fonts/calibre_font/Calibre-RegularItalic.otf
          style: italic
        
    - family: Calibre-Black
      fonts:     
        - asset: fonts/calibre_font/Calibre-Black.otf
        - asset: fonts/calibre_font/Calibre-BlackItalic.otf
          style: italic

    - family: Calibre-Bold
      fonts:    
        - asset: fonts/calibre_font/Calibre-Bold.otf
        - asset: fonts/calibre_font/Calibre-BoldItalic.otf
          style: italic

    - family: Calibre-Light
      fonts:      
        - asset: fonts/calibre_font/Calibre-Light.otf
        - asset: fonts/calibre_font/Calibre-LightItalic.otf
          style: italic

    - family: Calibre-Medium
      fonts:
        - asset: fonts/calibre_font/Calibre-Medium.otf
        - asset: fonts/calibre_font/Calibre-MediumItalic.otf
          style: italic

    - family: Calibre-Semibold
      fonts:
        - asset: fonts/calibre_font/Calibre-Semibold.otf
        - asset: fonts/calibre_font/Calibre-SemiboldItalic.otf
          style: italic

    - family: Calibre-Thin
      fonts:      
        - asset: fonts/calibre_font/Calibre-Thin.otf
        - asset: fonts/calibre_font/Calibre-ThinItalic.otf
          style: italic

    - family: Nova-Medium
      fonts: 
        - asset: fonts/aesthetic_nova/nova_medium.ttf
    
    - family: Nova-Bold
      fonts: 
        - asset: fonts/aesthetic_nova/nova_bold.ttf

    - family: Nova-Black
      fonts: 
        - asset: fonts/aesthetic_nova/nova_black.ttf

    - family: Nova-Light
      fonts: 
        - asset: fonts/aesthetic_nova/nova_light.ttf

    - family: Inter-V
      fonts: 
        - asset: fonts\inter_v\Inter-V.ttf

    - family: Inter-Bold
      fonts: 
        - asset: fonts\inter_v\Inter-Bold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
